# Testing pdblp Dummy Data Methods

In [1]:
import sys
sys.path.append("..")
import pdblp
print(pdblp.__version__)

# Create a dummy connection
con = pdblp.BCon(logdir='.', dummy=True)
con.start()

0.1.8+pinnaclefork.1

In [2]:
# Test bdh method
bdh = con.bdh(["JCI INDEX", "LQ45 INDEX"], ["PX_LAST", "PX_OPEN", "TURNOVER"], '20240101', '20240105')
con.log_request('bdh', ["JCI INDEX", "LQ45 INDEX"], ["PX_LAST", "PX_OPEN", "TURNOVER"])
display(bdh)

ticker        JCI INDEX                             LQ45 INDEX               \
field           PX_LAST      PX_OPEN     TURNOVER      PX_LAST      PX_OPEN
date
2024-01-01  2735.213661    33.734820   708.374975  2592.911449    33.015568
2024-01-02  1485.778964  2663.755771  6146.761168  7786.084609  9967.022166
2024-01-03  3382.554209  3375.008409  1603.197980  4388.876170  1900.303416
2024-01-04  7656.883843  6080.083293  8410.758384  9000.495385   214.256465
2024-01-05  3852.879817  2337.515424  5389.974118  2481.955654  3799.284503

ticker
field          TURNOVER
date
2024-01-01  2600.225861
2024-01-02  4320.748326
2024-01-03  3087.274051
2024-01-04  2177.434574
2024-01-05  8133.780994

In [3]:
# Test ref method
ref = con.ref(["BBCA IJ EQUITY", "TLKM IJ EQUITY"], ["EQY_INIT_PO_DT", "EQY_INIT_PO_SH_PX"])
con.log_request('ref', ["BBCA IJ EQUITY", "TLKM IJ EQUITY"], ["EQY_INIT_PO_DT", "EQY_INIT_PO_SH_PX"])
display(ref)

           ticker              field        value
0  BBCA IJ EQUITY     EQY_INIT_PO_DT   2000-01-01
1  BBCA IJ EQUITY  EQY_INIT_PO_SH_PX  1284.335512
2  TLKM IJ EQUITY     EQY_INIT_PO_DT   2000-01-01
3  TLKM IJ EQUITY  EQY_INIT_PO_SH_PX  3091.762291

In [4]:
# Test bulkref method
bulkref = con.bulkref(["JCI INDEX", "LQ45 INDEX"], ["INDEX_MEMBERS_SHARES", "INDX_MWEIGHT_PX"])
con.log_request('bulkref', ["JCI INDEX", "LQ45 INDEX"], ["INDEX_MEMBERS_SHARES", "INDX_MWEIGHT_PX"])
display(bulkref)

,ticker,field,name,value,position
0,JCI INDEX,INDEX_MEMBERS_SHARES,Index Member,dummy_Index Member,0
1,JCI INDEX,INDEX_MEMBERS_SHARES,Number of Shares,3146.841738,1
2,JCI INDEX,INDX_MWEIGHT_PX,Index Member,dummy_Index Member,0
3,JCI INDEX,INDX_MWEIGHT_PX,Percent Weight,4196.432578,1
4,JCI INDEX,INDX_MWEIGHT_PX,Actual Weight,8686.319699,2
5,JCI INDEX,INDX_MWEIGHT_PX,Current Price,431.538783,3
6,LQ45 INDEX,INDEX_MEMBERS_SHARES,Index Member,dummy_Index Member,0
7,LQ45 INDEX,INDEX_MEMBERS_SHARES,Number of Shares,8559.846192,1
8,LQ45 INDEX,INDX_MWEIGHT_PX,Index Member,dummy_Index Member,0
9,LQ45 INDEX,INDX_MWEIGHT_PX,Percent Weight,9515.255143,1
10,LQ45 INDEX,INDX_MWEIGHT_PX,Actual Weight,6573.894957,2
11,LQ45 INDEX,INDX_MWEIGHT_PX,Current Price,3861.943849,3