# Testing pdblp Dummy Data Methods

In [2]:
import sys
sys.path.append("..")
import pdblp
print(pdblp.__version__)

# Create a dummy connection
con = pdblp.BCon(logdir='.', dummy=True)
con.start()

0.1.8+pinnaclefork.1

In [ ]:
# Test bdh method
bdh = con.bdh(["JCI INDEX", "LQ45 INDEX"], ["PX_LAST", "PX_OPEN", "TURNOVER"], '20240101', '20240105')
display(bdh)

ticker        JCI INDEX
field           PX_LAST      PX_OPEN     TURNOVER
date
2024-01-01  2639.678568  9271.457209  9289.447977
2024-01-02  3108.568680  8702.458758  3108.321365
2024-01-03  9709.938688  9716.676887  4119.322663
2024-01-04   424.532119  7150.241019  9669.018991
2024-01-05  4938.505845  2264.756022  9478.932736

In [5]:
# Test ref method
ref = con.ref(["BBCA IJ EQUITY", "TLKM IJ EQUITY"], ["EQY_INIT_PO_DT", "EQY_INIT_PO_SH_PX"])
display(ref)

           ticker              field        value
0  BBCA IJ EQUITY     EQY_INIT_PO_DT   2000-01-01
1  BBCA IJ EQUITY  EQY_INIT_PO_SH_PX  9297.592874
2  TLKM IJ EQUITY     EQY_INIT_PO_DT   2000-01-01
3  TLKM IJ EQUITY  EQY_INIT_PO_SH_PX  7757.535064

In [7]:
# Test bulkref method
bulkref = con.bulkref(["JCI INDEX", "LQ45 INDEX"], ["INDEX_MEMBERS_SHARES", "INDX_MWEIGHT_PX"])
display(bulkref)

,ticker,field,name,value,position
0,JCI INDEX,INDEX_MEMBERS_SHARES,Index Member,dummy_Index Member,0
1,JCI INDEX,INDEX_MEMBERS_SHARES,Number of Shares,3728.376786,1
2,JCI INDEX,INDX_MWEIGHT_PX,Index Member,dummy_Index Member,0
3,JCI INDEX,INDX_MWEIGHT_PX,Percent Weight,4507.681977,1
4,JCI INDEX,INDX_MWEIGHT_PX,Actual Weight,9192.850486,2
5,JCI INDEX,INDX_MWEIGHT_PX,Current Price,6193.425,3
6,LQ45 INDEX,INDEX_MEMBERS_SHARES,Index Member,dummy_Index Member,0
7,LQ45 INDEX,INDEX_MEMBERS_SHARES,Number of Shares,2866.32234,1
8,LQ45 INDEX,INDX_MWEIGHT_PX,Index Member,dummy_Index Member,0
9,LQ45 INDEX,INDX_MWEIGHT_PX,Percent Weight,1644.020949,1
10,LQ45 INDEX,INDX_MWEIGHT_PX,Actual Weight,6896.108465,2
11,LQ45 INDEX,INDX_MWEIGHT_PX,Current Price,597.268597,3